name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      
    - name: Debug workflow
      run: pwd; echo "printed working directory"; ls -lart; echo "end of debug step";
    
    - name: Install dependencies      
      run: pwd; echo "printed working directory"; dotnet restore ./src/TournamentTracker.sln
    
    - name: Build
      #run: dotnet build ./src/TournamentTracker.sln --configuration Release --no-restore
      run: msbuild ./src/TournamentTracker.sln /t:Restore /p:Configuration=$env:Configuration
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
